# Generated by Django 3.2.8 on 2022-02-17 15:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_auto_20211026_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiriConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Siri voice commands configuration', max_length=50)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoiceCommand',
            fields=[
                ('unique_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('change_state', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off')], max_length=10)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voice_command', to='devices.device')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
