# Generated by Django 4.0.3 on 2022-03-13 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicecommand',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='voice_command', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siriconfiguration',
            name='name',
            field=models.CharField(default='Siri voice commands', max_length=50),
        ),
    ]
