# Generated by Django 4.0.3 on 2022-11-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siri', '0002_voicecommand_user_alter_siriconfiguration_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='siriconfiguration',
            name='api_key',
            field=models.CharField(default='secret key', max_length=255),
        ),
    ]
